repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v2.0.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: check-ast
    - id: check-merge-conflict
    - id: debug-statements
    - id: flake8
    - id: name-tests-test
