language: python
sudo: false

python:
  - 3.5
  - 3.6

install:
  - pip install pipenv
    # Should we install the dev dependencies as well?
  - pipenv install
    # Tox runs within the virtualenv created by Pipenv
  - pipenv run pip install tox

before_script:
  - pipenv run pip freeze

script:
  - pipenv run tox -v

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - coveralls
  - source .tox/py3/bin/activate; vast -h
