language: python
sudo: false

python:
  - 3.5
  - 3.6

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  - pipenv graph

script:
  - pipenv run pre-commit run -av
  - pipenv run nosetests --with-coverage --cover-erase --cover-package=src.net,src.metadata

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - coveralls
  - source .tox/py3/bin/activate; vast -h
