language: python 
sudo: false

python:
        - "3.5"

before_script:
        - pip freeze

script:
        - tox -v

after_success:
        - cd ${TRAVIS_BUILD_DIR}
        - coveralls
        - source .tox/py3/bin/activate; vast -h
