language: python
sudo: false

python:
  - 3.5
  - 3.6

install:
  - pip install pipenv
    # Should we install the dev dependencies as well?
    #- pipenv install
    # Tox runs *outside* the virtualenv created by Pipenv?!
    # Maybe this is enough for tox-pipenv to do the right thing?
  - pip install tox

before_script:
  - pipenv run pip freeze

script:
  # Tox is installed outside the virtualenv we've created through pipenv
  - tox -v

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - coveralls
  - source .tox/py3/bin/activate; vast -h
