language: python
sudo: false

python:
  - 3.5
  - 3.6

install:
  - pip install pipenv tox tox-pipenv

before_script:
        - pip freeze

script:
        - tox -v

after_success:
        - cd ${TRAVIS_BUILD_DIR}
        - coveralls
        - source .tox/py3/bin/activate; vast -h
